### ISSUE TITLE
Throttling mechanism does not allow to cancel timers. 

### ISSUE THREAD

**Issue by Czaki** [pyapp-kit/superqt#113]
**Describe the bug**

lack of possibility to stop timer behind throttling mechanism may lead to failing of strict tests like in napari by keep objects alive 

https://github.com/napari/napari/runs/8043907763?check_suite_focus=true#step:8:377

**To Reproduce**

**Expected behavior**

There should be option to stop timer on close. 

**Screenshots**
Screenshots and GIFS are much appreciated when reporting visual bugs.

**Desktop (please complete the following information):**
 - OS with version [e.g macOS 10.15.7]
 - Qt Backend [e.g PyQt5, PySide2]
 - Python version

**Comment by tlambert03** [comment]
how would you fix this @Czaki?  we could just  make the `_timer` public?

**Comment by Czaki** [comment]
I would rather change flush to have signature: `flush(self, restart_timer=True)` 
https://github.com/pyapp-kit/superqt/blob/599dff7d029ce0499f73d52b61769358fb7ae346/src/superqt/utils/_throttler.py#L142

To allow flush all events and stop timer.

**Comment by tlambert03** [comment]
That works for me!
