### ISSUE TITLE
Dev install failing, no matching distribution for pyside2

### ISSUE THREAD

**Issue by alisterburt** [pyapp-kit/superqt#145]
**Describe the bug**

Super minor but running `pip install -e .[dev]` locally fails for me with

```txt
ERROR: Could not find a version that satisfies the requirement pyside2 (from versions: none)
ERROR: No matching distribution found for pyside2
```

Not sure if this is an M1 thing or if the package is just misspecified

**Comment by tlambert03** [comment]
can you install pyside with `pip install pyside2`? are you on py3.11?

**Comment by alisterburt** [comment]
Yeah that's what's causing the fail (for whatever reason), 3.10 still for me!

```
(superqt) ➜  superqt git:(listview) ✗ python -V                                  
Python 3.10.8
(superqt) ➜  superqt git:(listview) ✗ pip install pyside2
ERROR: Could not find a version that satisfies the requirement pyside2 (from versions: none)
ERROR: No matching distribution found for pyside2
```

**Comment by tlambert03** [comment]
yeah, all the mac wheels specify intel: https://pypi.org/project/PySide2/#files

 ... so I assume that's it

anyway, not a superqt issue :)
