### ISSUE TITLE
Add elided `QLineEdit` class

### ISSUE THREAD

**Issue by dalthviz** [pyapp-kit/superqt#152]
Hi, while working on https://github.com/napari/napari/pull/5640 I ended up checking a way to add eliding capabilities to a `QLineEdit` at https://github.com/napari/napari/pull/5665 

Following the discussion (https://github.com/napari/napari/pull/5665#issuecomment-1483374558), could it be worthy to add here something like an [`ElidingLineEdit` class](https://github.com/napari/napari/blob/d9e3b5c604116cfcb8eeed2527ef803828172806/napari/_qt/widgets/qt_dims_slider.py#L31-L107)?

**Comment by tlambert03** [comment]
sure, there is already an [ElidingLabel](https://github.com/pyapp-kit/superqt/blob/main/src/superqt/_eliding_label.py)

somehow the idea of an editable elided text feels a little funny from a UI perspective, (it's a hard problem of course, but I guess I imagine that one wants to always _see_ the thing they're editing, even if it will later be shown with ellipses somewhere).  but if you found a need for it in napari and want to upstream it here, by all means :)

Even better if you can combine the logic into a single base or mixin class?

**Comment by dalthviz** [comment]
Thank you for the quick response! I will look into having some base class for the label and the line edit :+1:

Following that, and regarding the possible code organization, maybe the file structure should look something like:

```
.
└── src/
    └── superqt/
        └── elidable/
            ├── __init__.py (exposes widgets with eliding capabilities)
            ├── _eliding_label.py (contains current ElidingLabel class refactored)
            ├── _eliding_line_edit.py (contains ElidingLineEdit class)
            └── _eliding.py (contains base/mixin class)

```
?

**Comment by tlambert03** [comment]
Sure!
