### ISSUE TITLE
Exporting python script with QRangeSlider with pyinstaller, the latter doesn't work properly when it is dragged and dropped

### ISSUE THREAD

**Issue by dadep88** [pyapp-kit/superqt#155]
I have a script creating a simple GUI using QRangeSlider, however if I convert it in a standalone .exe with pyinstaller, the slider drag and drop  functionalities don't work properly. In particular, if I drag and drop the slider in the middle, I would expect the slider move rigidly, while only one of the two handlers moves.

**Comment by tlambert03** [comment]
Thanks for reporting.  It will take me some time to get around to this.  If you have a minimal reproducible example (a repo that I can quickly build with pyinstaller) that would greatly facilitate the debugging process.

**Comment by dadep88** [comment]
Trying to replicating this issue I understood that it was an error in my implementation

**Comment by tlambert03** [comment]
thank's for letting me know!
