### ISSUE TITLE
QLabeledDoubleSlider text input broken

### ISSUE THREAD

**Issue by bauerdavid** [pyapp-kit/superqt#166]
**Describe the bug**
Editing the slider value using the text input field doesn't work correctly. If I input a non-integer value (having some nonzero decimal values), it is converted to an int.

**To Reproduce**
1. Create a QLabeledDoubleSlider with a range of 0-1 (if you have napari installed, you can use the opacity parameter of a layer)
2. Write `0.5` into the text field of the slider and press Enter.
3. Notice that the value is immediately converted to 0.0
4. Write `0.5` into the text field again.
5. This time the text field keeps this value, but the slider is not updated, meaning the slider value is in fact not updated (in napari you can easily verify it by checking the `opacity` value of the layer in the console)

**Expected behavior**
The input value shouldn't be casted to int

**Screenshots**
Original state:
![image](https://github.com/pyapp-kit/superqt/assets/36735863/a38b1f79-df0b-4b4d-b39b-dee11650b19f)
After writing 0.5 and pressing Enter:
![image](https://github.com/pyapp-kit/superqt/assets/36735863/5c53ecac-f043-4030-9933-104682a9a1ba)
After writing 0.5 and pressing Enter again:
![image](https://github.com/pyapp-kit/superqt/assets/36735863/2be53eae-650d-4d3a-93f3-61a16cecf09c)

**Desktop (please complete the following information):**
 - Windows 11
 - PyQt5==5.15.9
 - Python 3.10.11

**Potential fix:**
I was able to fix this for my own project by adding the following function to `QLabeledDoubleSlider`:
```python
def _setValue(self, value: float):
    self._slider.setValue(value)
```
This works because `QLabeledDoubleSlider` inherits from `QLabeledSlider`, which converts the input value to `int` before setting it to the slider.

**Comment by tlambert03** [comment]
thanks @bauerdavid ... looks like this was a regression introduced in https://github.com/pyapp-kit/superqt/pull/106

will have a fix soon
