### ISSUE TITLE
Focus events getting lost?

### ISSUE THREAD

**Issue by RT-Tap** [pyapp-kit/superqt#174]
Hey, I need something to update when a widget looses focus and I can do that with something simple like 
````
class CustomRangeSlider(QtWidgets.QSlider):
    def focusOutEvent(self, event):
        # Call the base class focusOutEvent method
        super().focusOutEvent(event)
        # Handle the focus loss here
        print("lost focus")
```` 
But if I try that with any superqt slider it looks like this signal is never sent? Or is superseded or intercepted by something?

I tried setting the Focus Policy using
`rangeSlider.setFocusPolicy(Qt.FocusPolicy.ClickFocus)`

and tried looking at events by using 
```
class QLabeledRangeSlider_(QLabeledRangeSlider):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
    def event(self, ev: QEvent) -> bool:
        print("_"*20)
        print(f"{ev.type()}")
        print("_"*20)
        if ev.type() in [QEvent.Type.FocusIn, QEvent.Type.FocusOut]:
            print("Focused in/out")
        if ev.type() == QEvent.Type.WindowActivate:
            self.update()
        elif ev.type() in (QEvent.Type.HoverEnter, QEvent.Type.HoverMove):
            self._updateHoverControl(self._event_position(ev))
        elif ev.type() == QEvent.Type.HoverLeave:
            self._hoverControl = QtWidgets.QStyle.SubControl.SC_None
            lastHoverRect, self._hoverRect = self._hoverRect, QRect()
            self.update(lastHoverRect)
        return super().event(ev)
```
But I just don't understand what is going on or why the focus event wouldnt be showing up anywhere.
I'm really lost here if anyone could point me in the right direction I would really appreciate it.

**Comment by tlambert03** [comment]
hi and thanks for the clear issue.

Interestingly, your first example *also* doesn't work if you subclass from `QAbstractSlider` (which is what we subclass for our sliders):

```python
class CustomRangeSlider(QtWidgets.QAbstractSlider):
    def focusOutEvent(self, event):
        # Call the base class focusOutEvent method
        super().focusOutEvent(event)
        # Handle the focus loss here
        print("lost focus")
```

so I need to look into the C code to see why it's different.

**Comment by tlambert03** [comment]
aha, it's this line right here:

https://github.com/qt/qtbase/blob/568ab62185bfa7876db4d8804101a8f946b04898/src/widgets/widgets/qslider.cpp#L46

will add it to our own labeled sliders.

**Comment by tlambert03** [comment]
#175 should fix it for you, but in the meantime, and until the next release, you should be able to fix it locally by calling:

```python
slider.setFocusPolicy(QtCore.Qt.FocusPolicy.TabFocus)
```
on your slider instance
